"""empty message

Revision ID: 167a6a72aeed
Revises: 2958ee784357
Create Date: 2020-05-12 10:04:52.574383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167a6a72aeed'
down_revision = '2958ee784357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'date')
    # ### end Alembic commands ###
