"""empty message

Revision ID: b20a1d70d419
Revises: 167a6a72aeed
Create Date: 2020-05-12 10:29:23.727974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20a1d70d419'
down_revision = '167a6a72aeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'case', 'user', ['user_id'], ['id'])
    op.add_column('conference', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('contest', sa.Column('end', sa.Date(), nullable=True))
    op.add_column('contest', sa.Column('start', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'start')
    op.drop_column('contest', 'end')
    op.drop_column('conference', 'date')
    op.drop_constraint(None, 'case', type_='foreignkey')
    op.drop_column('case', 'user_id')
    # ### end Alembic commands ###
