"""empty message

Revision ID: dc4fff7d0fe4
Revises: de0b227be0b2
Create Date: 2020-05-14 13:59:09.894596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc4fff7d0fe4'
down_revision = 'de0b227be0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipes', sa.Column('images', sa.String(length=255), nullable=True))
    op.drop_column('recipes', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('recipes', 'images')
    op.drop_table('ads')
    # ### end Alembic commands ###
